name: Build Client and Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install client dependencies
        run: |
          cd client
          npm ci

      - name: Build client
        run: |
          cd client
          npm run build

      - name: Install server dependencies
        run: |
          cd server
          npm ci

      - name: Build server (if applicable)
        run: |
          cd server
          # Add build command if needed, e.g., npm run build
          echo "No build step for server"

      - name: Upload client build artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: client/build

      - name: Upload server artifact
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: server
