name: Docker Package

description: |
  This workflow builds a Docker image containing both the client build and the server, then stores the image as an artifact.

runs:
  using: "docker"
  image: "docker/Dockerfile"

inputs:
  tag:
    description: "Tag for the Docker image"
    required: false
    default: "latest"

outputs:
  image:
    description: "Built Docker image"
    value: ${{ steps.build.outputs.image }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build -t subarr:${{ inputs.tag }} -f docker/Dockerfile .
      - name: Save Docker image as artifact
        run: |
          docker save subarr:${{ inputs.tag }} | gzip > subarr-image.tar.gz
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: subarr-docker-image
          path: subarr-image.tar.gz
